### ISSUE TITLE
Compiled with 4 warnings

### ISSUE THREAD

**Issue by tim-phillips** [zeit/now-env#11]
`now-env` triggers warnings in webpack. I'm seeing this while using `next.js`:

```
warning  in ./node_modules/now-env/lib/load-secrets.js
12:11-31 Critical dependency: the request of a dependency is an expression

warning  in ./node_modules/now-env/lib/load-required.js
12:11-33 Critical dependency: the request of a dependency is an expression

warning  in ./node_modules/now-env/lib/load-now-json.js
15:20-37 Critical dependency: the request of a dependency is an expression

warning  in ./node_modules/now-env/lib/load-pkg-json.js
15:20-37 Critical dependency: the request of a dependency is an expression
```

**Comment by tim-phillips** [comment]
https://github.com/webpack/webpack/issues/196

**Comment by sergiodxa** [comment]
now-env is expected to be used server side (only in Node) and not client side because it reads the now.json dynamically from the disk (that the reason for that error).

To use it with webpack you should require now-env inside your webpack.config.js and pass env variables to your app with the webpack plugins [DefinePlugin](https://webpack.js.org/plugins/define-plugin/) or [EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/).

For the usage with Next.js check the [with-now-env example](https://github.com/zeit/next.js/tree/canary/examples/with-now-env).
