### ISSUE TITLE
Enforce prefix for secrets

### ISSUE THREAD

**Issue by leo** [zeit/now-env#3]
If people use this anywhere for secrets:

```json
{
  "my-secret-key": "keep-it-secret"
}
```

Instead of this:

```json
{
  "@my-secret-key": "keep-it-secret"
}
```

We should throw an error.

The prefix is not really needed, but it makes it much more consistent. If you use `@` in some places and in some others not, you might not always think they're secrets.

**Comment by sergiodxa** [comment]
Well supporting without the `@` was technically more code (https://github.com/zeit/now-env/blob/master/lib/get-value.js#L13), because I need to remove the `@` from the secret name. We can throw an error for sure, and also implement `err.sh` for that error and https://github.com/zeit/now-env/blob/master/lib/get-value.js#L34 that one.

**Comment by leo** [comment]
Sounds good to me 👍
